# Generated by Django 2.2.1 on 2020-03-20 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200312_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
