# Generated by Django 3.0.4 on 2020-03-23 08:10

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
