# Generated by Django 2.2.1 on 2020-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200312_1756'),
        ('authentication', '0002_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ManyToManyField(to='blog.Status'),
        ),
    ]
